// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0cQi-eDTBgge-wPwk_ogI5f-xtMNXH6o',
    appId: '1:692595540299:web:3a8fcbc7a6eb23734928ce',
    messagingSenderId: '692595540299',
    projectId: 'hoothub-8a56e',
    authDomain: 'hoothub-8a56e.firebaseapp.com',
    storageBucket: 'hoothub-8a56e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClr_sSo9TGLB_K3wYK8L0sZGkGFZLijLY',
    appId: '1:692595540299:android:1a4be769063e75e84928ce',
    messagingSenderId: '692595540299',
    projectId: 'hoothub-8a56e',
    storageBucket: 'hoothub-8a56e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvYZB9pzUBwS0K7ZK530P4ziVG7eVt4Kg',
    appId: '1:692595540299:ios:43bb53eb3aafce6c4928ce',
    messagingSenderId: '692595540299',
    projectId: 'hoothub-8a56e',
    storageBucket: 'hoothub-8a56e.appspot.com',
    iosBundleId: 'com.example.hoothub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvYZB9pzUBwS0K7ZK530P4ziVG7eVt4Kg',
    appId: '1:692595540299:ios:43bb53eb3aafce6c4928ce',
    messagingSenderId: '692595540299',
    projectId: 'hoothub-8a56e',
    storageBucket: 'hoothub-8a56e.appspot.com',
    iosBundleId: 'com.example.hoothub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0cQi-eDTBgge-wPwk_ogI5f-xtMNXH6o',
    appId: '1:692595540299:web:2268d46a57e6d0254928ce',
    messagingSenderId: '692595540299',
    projectId: 'hoothub-8a56e',
    authDomain: 'hoothub-8a56e.firebaseapp.com',
    storageBucket: 'hoothub-8a56e.appspot.com',
  );

}